[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = ["python3 -m ensurepip", "pip install -r api/requirements.txt"]

[start]
cmd = "cd api && uvicorn app:app --host 0.0.0.0 --port $PORT"
